### ISSUE TITLE
Crash with MBRecognizerRunnerViewController

### ISSUE THREAD

**Issue by jowinst** [blinkcard/blinkcard-ios#11]
## What?

We are experiencing some crashes which seem to occur after displaying `MBRecognizerRunnerViewController`. Our crash stack trace looks like:

3 `-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]`
2 `+[_CFXNotificationTokenRegistration keyCallbacks]`
1 `objc_exception_throw`

We have logs in each app screen, and the flow always look pretty similar. Consider that we have defined `MBRecognizerRunnerViewController` with screen name `card_camera_reader`. You can see in the examples that after passing through this screen, couple of secs afterwards a crash occurs:

| Example 1 | Example 2 | Example 3 | Example 4 |
| --- | --- | --- | --- |
| <img width="1159" alt="Screenshot 2020-09-17 at 12 12 00" src="https://user-images.githubusercontent.com/16885901/93474578-d1e0c280-f8f7-11ea-8a8f-f6d6b83bb00f.png"> | <img width="1247" alt="Screenshot 2020-09-17 at 12 11 52" src="https://user-images.githubusercontent.com/16885901/93474610-defdb180-f8f7-11ea-8da5-cc604309c669.png"> | <img width="1104" alt="Screenshot 2020-09-17 at 12 11 44" src="https://user-images.githubusercontent.com/16885901/93474645-eb820a00-f8f7-11ea-8481-04a4688650df.png"> | <img width="965" alt="Screenshot 2020-09-17 at 12 11 36" src="https://user-images.githubusercontent.com/16885901/93474671-f472db80-f8f7-11ea-95a4-70fb23c5f12e.png"> |

## Observations

1. We have the hypothesis that the stack trace is a result of symbolication failure. Good symbolication is hard, so issues like this are not uncommon in third-party crash reporters.
2. After reading different articles, I conclude that UI issues frequently result in that stack trace:
     * https://developer.apple.com/forums/thread/120161
     * https://github.com/wordpress-mobile/WordPress-iOS/issues/10354
     * https://github.com/wordpress-mobile/WordPress-iOS/issues/10571

I would really appreciate if you are able to help us with this issue considering that it's now affecting the user experience in Verse app:

<img width="399" alt="Screenshot 2020-09-16 at 12 05 16" src="https://user-images.githubusercontent.com/16885901/93480402-b1b40200-f8fd-11ea-99ee-6ae9e59f48a7.png">

**Comment by juraskrlec** [comment]
Hi @jowinst 

could you please tell me the flow of your app, when are you showing MBRecognizerRunnerViewController? Do you pause scanning and resume it? Do you have any Sample application where this crash is occurring? Can you reproduce this crash while testing your app, and if yes, what are the steps to reproduce it?

**Comment by juraskrlec** [comment]
Hi @jowinst 
Just checking if you've seen our questions?

**Comment by mparadina** [comment]
Hi @jowinst 

As this issue is currently inactive, I am closing it.
Feel free to reopen it, or contact us directly at support@microblink.com if anything comes up.
