### ISSUE TITLE
Test plans fail to build

### ISSUE THREAD

**Issue by yaakovgamliel** [blinkcard/blinkcard-ios#16]
Hi,
We encounter an issue after integrating Microblink libraries, BlinkId and BlinkCard, we are able to build, run and archive our app, but we can not build the app for test plans, when we try to run any test, we get the following error:
```
Multiple commands produce '/Users/ygdev/Library/Developer/Xcode/DerivedData/Sunbit-gqkznxfxghbfkwbgncsntljjorfr/Build/Products/Debug-iphonesimulator/cocoapods-artifacts-Debug.txt':
1) That command depends on command in Target 'pos' (project 'pos'): script phase “[CP] Prepare Artifacts”
2) That command depends on command in Target 'posTests' (project 'pos'): script phase “[CP] Prepare Artifacts”
```
We observed that adding these 2 libraries via CocoaPods adds the following phase to all targets in the project:
```
               10E29A52893222C8752510C3 /* [CP] Prepare Artifacts */ = {
                       isa = PBXShellScriptBuildPhase;
                       buildActionMask = 2147483647;
                       files = (
                       );
                       inputPaths = (
                               "${PODS_ROOT}/Target Support Files/Pods-pos demo/Pods-pos demo-artifacts.sh",
                               "${PODS_ROOT}/MBBlinkCard/BlinkCard.xcframework",
                               "${PODS_ROOT}/PPBlinkID/Microblink.xcframework",
                       );
                       name = "[CP] Prepare Artifacts";
                       outputPaths = (
                               "${BUILT_PRODUCTS_DIR}/cocoapods-artifacts-${CONFIGURATION}.txt",
                       );
                       runOnlyForDeploymentPostprocessing = 0;
                       shellPath = /bin/sh;
                       shellScript = "\"${PODS_ROOT}/Target Support Files/Pods-pos demo/Pods-pos demo-artifacts.sh\"\n";
                       showEnvVarsInLog = 0;
               };
```
Application details:
-------------------
Xcode v12.3
```
pod 'PPBlinkID', '~> 5.9.0'
pod 'MBBlinkCard', '~> 2.0.0'
```

**Comment by yaakovgamliel** [comment]
We solved the issue after upgrading to v1.10.0 in CocoaPods and deleting and re-creating the workspace, the previous added `[CP] Prepare Artifacts` step was automatically removed then.
Keeping this here for other users encountering this issue.

**Comment by mparadina** [comment]
Hi @yaakovgamliel 

Thank you for the feedback!

Yes, for implementing BlinkCard to your project via CocoaPods, you would need to update CocoaPods to version 1.10.0, or newer.

Just to note here as well, this is mentioned in the Release notes in the BlinkCard 2.0.0 update:
https://github.com/blinkcard/blinkcard-ios/blob/master/Release%20notes.md#cocapods-support-change

Also, if you have any other additional questions, feel free to ask.

Regards,
Milan

**Comment by mparadina** [comment]
Hi @yaakovgamliel 

As this issue is inactive, I am closing it.
If anything comes up, feel free to reopen the ticket, or contact us directly at support@microblink.com
