### ISSUE TITLE
Unable to install the SDK via SPM

### ISSUE THREAD

**Issue by yaakovgamliel** [blinkcard/blinkcard-ios#17]
Hi,
I got the following error while trying to install the SDK with Swift Package Manager.
Error:
```
Showing All Messages
downloaded archive of binary target 'BlinkCard' does not contain expected binary artifact 'BlinkCard.xcframework'

```
Xcode 12.3

**Comment by mijo-gracanin** [comment]
Hi @yaakovgamliel ,
I re-uploaded BlinkCard.xcframework.zip. Can you please tell me if install via SPM works for you now?

**Comment by yaakovgamliel** [comment]
Hi @mijo-gracanin ,
Is working as expected now, thank you for the quick response

**Comment by udaik542** [comment]
Hi @mijo-gracanin I am getting the same error "
Showing Recent Messages
downloaded archive of binary target 'MyDemoPackage' does not contain expected binary artifact 'MyDemoPackage'
"
I uploaded again but not luck
