### ISSUE TITLE
Direct processing API always returns empty

### ISSUE THREAD

**Issue by mureatencio** [blinkcard/blinkcard-ios#22]
I followed the readme documentation to set up a scanner example.
The scanner overlay view controller works well but the direct processing API always returns empty.

`func recognizerRunner(_ recognizerRunner: MBCRecognizerRunner, didFinishScanningWith state: MBCRecognizerResultState)` always returns empty results.

![Screen Shot 2021-06-16 at 11 36 33](https://user-images.githubusercontent.com/2531394/122266591-2caf4680-ce97-11eb-9fbe-4207a27511f9.png)

Does this API require an additional setup?

**Comment by mparadina** [comment]
Hi @mureatencio 

Which state is being returned after you take a picture of the card?
Do you get "Valid!" or "Invalid!" in the console?

Also to ask, did you try putting the `cameraFrame` to `false` and seeing if you can get the results?

Regards,
Milan

**Comment by mureatencio** [comment]
Hi @mparadina,
thanks for the advice,

This is the state I'm getting (always invalid):
`(lldb) p recognizer?.result.resultState`
`(MBCRecognizerResultState?) $R4 = empty`

I tried setting `cameraFrame` to `false`, but getting the same result.

**Comment by mparadina** [comment]
Hi @mureatencio 

Which information do you want to extract from the card?
I can see that you're only giving one side of the card to the DirectAPI processing. On that side, I can see there are only the card number, date of expiry and card owner name. If you're not interested in any other information, you can disable the extraction of that information. 
You can add these lines in the `setupRecognizerRunner()` below the line `recognizer = MBCBlinkCardRecognizer()`:
```
   blinkCardRecognizer.extractCvv = false
   blinkCardRecognizer.extractIban = false
```

If you did not disable the information which you do not need, the SDK still requires the other side of the card in order to finish the scanning process.

If you require both sides, you need to implement the `recognizerRunnerDidFinishRecognition(ofFirstSide recognizerRunner: MBCRecognizerRunner)` method, where you will need to open the image picker to give the Direct API the other side of the card.

An example code:

```
extension ViewController: MBCFirstSideFinishedRecognizerRunnerDelegate {
    
    func recognizerRunnerDidFinishRecognition(ofFirstSide recognizerRunner: MBCRecognizerRunner) {
       print("Scanned the first side of the card!")
        DispatchQueue.main.async {
        //method to open the image picker
            self.openImagePicker()
        }
    }
}
```

If that does not help, would you mind sharing all of the code connected to the SDK and how do you setup the Direct API so that we can reproduce the issue on our end?

Regards,
Milan

**Comment by mureatencio** [comment]
Hi, thanks for the follow-up.

I followed the steps but it's still returning `empty`.

I uploaded the project so you can test the implementation I did. 

I replaced the License key string to avoid uploading it.

The project can be found here: https://github.com/mureatencio/microblink_poc

**Comment by mparadina** [comment]
Hi @mureatencio 

After some debugging, I realised that the main issue is with the sample you're sending to the Direct API.

The first issue is that you're setting the `extractCvv`  `extractIban` to the `blinkCardRecognizer` variable, but placing the `recognizer` variable into the recognizers array, leaving it unmodified.

So the sample code [here](https://github.com/mureatencio/microblink_poc/blob/master/POCMicroblink/ViewController.swift#L36-L46) would be: 
```
    func setupRecognizerRunner() {
        var recognizers = [MBCRecognizer]()
        recognizer = MBCBlinkCardRecognizer()
        recognizer?.extractCvv = false
        recognizer?.extractIban = false
        
        recognizers.append(recognizer!)
        let recognizerCollection = MBCRecognizerCollection(recognizers: recognizers)
        recognizerRunner = MBCRecognizerRunner(recognizerCollection: recognizerCollection)
        recognizerRunner?.scanningRecognizerRunnerDelegate = self
    }
```
I've checked the state of the recognizer after the scanning is complete, and the state is returned as `uncertain`. When the recognizer enters this state, this means that it did not manage to extract all of the information from the card. 

Once I've sent real cards to the Direct API, the state was returned as `valid` and all of the information was extracted.

For future testing, you can check out in which state the recognizer is in after the scanning process has finished like this:
```
    func recognizerRunner(_ recognizerRunner: MBCRecognizerRunner, didFinishScanningWith state: MBCRecognizerResultState) {
        let result = recognizer?.result
        if state == .valid  {
            print("Valid, all information extracted")
            print(result?.cardNumber)
            
        } else if state == .stageValid{
            print("Stage Valid, send the other side of the card for extraction")
            
        } else if state == .uncertain {
            print("Uncertain, some information was not extracted")
            
            let status = result?.processingStatus
            if status == .fieldIdentificationFailed {
                print("Field identification failed")
            }
        } else if state == .empty {
            print("Empty, did not manage to extract any information")
        }
    }
```
In the sample, you can also the variable `status`, which is referring to the processing status within the BlinkCard recognizer's result. 
With it, you can, for instance, check why the scanning process had issues with information extraction. In this case, the recognizer failed to identify the information from a particular field in the sample.

Also to add, I recommend testing the SDK with real cards to get the best out of the scanning process.

Let me know if you have any additional questions.

Regards,
Milan
