### ISSUE TITLE
Localization documentation for iOS seems to be outdated

### ISSUE THREAD

**Issue by luiszambon** [blinkcard/blinkcard-ios#26]
Hello.
Seems like the localization documentation posted on Github is outdate. 
I'm following the steps posted there, but it doesn't work.

My doubt is: How can I insert the localization file?

My code:
`let settings: MBCBlinkCardOverlaySettings = MBCBlinkCardOverlaySettings()
        settings.enableEditScreen = false

        /** Crate recognizer collection */
        let recognizerList = [CardScanHandler.blinkCardRecognizer!]
        let recognizerCollection: MBCRecognizerCollection = MBCRecognizerCollection(recognizers: recognizerList)

        /** Create your overlay view controller */
        let blinkCardOverlayViewController = MBCBlinkCardOverlayViewController(
            settings: settings,
            recognizerCollection: recognizerCollection,
            delegate: cardScanOverlayViewControllerDelegate)

        /** Create recognizer view controller with wanted overlay view controller */
        let recognizerRunneViewController: UIViewController = MBCViewControllerFactory.recognizerRunnerViewController(withOverlayViewController: blinkCardOverlayViewController)!
`

Your github:
<img width="1279" alt="Captura de Tela 2021-11-16 às 13 09 04" src="https://user-images.githubusercontent.com/41161270/142022294-f3df8de6-1459-45d1-95bd-f52b472a44bd.png">

**Comment by mparadina** [comment]
Hi @luiszambon 

There are a few ways to change the strings in the SDK.

As mentioned in the documentation, you can change the localisation file with the `language` property.
To change the language to be French, you would need to place "fr":
`MBCMicroblinkApp.shared().language = "fr"`

The localisation files are `.strings` files located in the `BlinkCard.xcframework`.
So, for instance, if you wanted to change a string in the English localisation file, you would need to go to:
BlinkCard.xcframework > ios-arm64_armv7 (os simulator/maccatalyst) > Resources > **en.strings**
Once you open the file, there you can see all of the strings which can be displayed in the English language.

Also, you could create your own localisation file, where you need to add all of the keys (a key is, for instance: "blinkcard_overlay_camera_too_high_message", which can be found in all of the .strings files) and add your own strings and name the file, for instance, myLocalisationFile.strings

However, you would need to place this file before you are initialising the SDK. 
For instance, you could place it in the `AppDelegate`, or in the `viewDidLoad()`

So, the line of code would look like:
`MBCMicroblinkApp.shared().language = "myLocalisationFile"`

A second way of changing the strings are via the MBCBlinkCardOverlaySettings:
```
        let blinkCardOverlaySettings = MBCBlinkCardOverlaySettings()
        blinkCardOverlaySettings.frontSideMessage = "Your front side message"
        blinkCardOverlaySettings.backSideMessage = "your backside message"
```

Let me know if this helped.

**Comment by luiszambon** [comment]
Thank you for the fast response, we will try again.

**Comment by mparadina** [comment]
Of course, let me know if you have any additional questions.

**Comment by luiszambon** [comment]
Hello, We still having problems, because we are not using this class `MBCMicroblinkApp`, we use `MBCMicroblinkSDK`, so we don't have access to the method you said.

**Comment by luiszambon** [comment]
Hi, we found a way to do it. Thanks for you support.
