### ISSUE TITLE
Unable to find a specification for `MBBlinkCard (~> 1.0.1)`

### ISSUE THREAD

**Issue by juange87** [blinkcard/blinkcard-ios#4]
After adding the pod, I got:

```
[!] Unable to find a specification for `MBBlinkCard (~> 1.0.1)
```

**Comment by dCubelic** [comment]
Hi,

sorry for the late reply, but did you manage to get the pod working?
I just tried adding the MBBlinkCard 1.0.1 pod to a new project and everything worked smoothly.

Let me know if you are still running in some problems.

Best regards,
Dominik

**Comment by digivi13** [comment]
I just had the same issue, resolved by updating your pod using "pod repo update" at the terminal. Should be able to run pod install just fine after that

**Comment by digivi13** [comment]
I think this can be closed
