### ISSUE TITLE
License has expired for Sample Project

### ISSUE THREAD

**Issue by AntonGolikov** [blinkcard/blinkcard-ios#6]
I was trying to check is the framework will suit my needs, but apparently the license key in Sample Project has expired on December 11 2019. Could you please update it?

**Comment by Cerovec** [comment]
Hi @AntonGolikov,

The license key in the sample app was updated with our latest releases, v1.1 and v1.1.1 this week. 

You can also always contact us at support@microblink.com to get trial licenses, or you can get them by registering on microblink.com/login.

Please let us know if there's something else we can help you with!

Thanks,
Jurica.
